# Generated by Django 3.1.5 on 2021-08-07 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('image', models.ImageField(default='', upload_to='uploads')),
                ('city', models.CharField(default='', max_length=50)),
                ('base', models.CharField(choices=[('veg', 'veg'), ('Nonveg', 'Nonveg'), ('both', 'both')], default='', max_length=50)),
                ('mobile', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=80)),
                ('image', models.ImageField(blank=True, default='', upload_to='uploads/dishes')),
                ('imagelink', models.CharField(default='', max_length=1400)),
                ('price', models.PositiveIntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='zomatoapp.category')),
                ('resturant', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='zomatoapp.resturant')),
            ],
        ),
    ]
