# Generated by Django 3.1.5 on 2021-08-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomatoapp', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturant',
            name='reststatus',
            field=models.CharField(choices=[('open', 'open'), ('close', 'close')], default='', max_length=100),
        ),
    ]
