# Generated by Django 3.1.5 on 2021-08-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomatoapp', '0003_resturant_reststatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturant',
            name='image1',
            field=models.ImageField(default='', upload_to='uploads'),
        ),
    ]
