# Generated by Django 3.1.5 on 2021-08-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomatoapp', '0004_resturant_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturant',
            name='timingend',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resturant',
            name='timingstart',
            field=models.CharField(default='', max_length=100),
        ),
    ]
