# Generated by Django 3.1.5 on 2021-08-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomatoapp', '0005_auto_20210810_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='imagelink',
            field=models.CharField(blank=True, default='', max_length=1400),
        ),
    ]
