# Generated by Django 3.1.5 on 2021-08-14 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zomatoapp', '0006_auto_20210810_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=400, null=True)),
                ('order_id', models.CharField(blank=True, max_length=400, null=True)),
                ('status', models.CharField(choices=[('success', 'success'), ('fail', 'fail')], max_length=100)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='zomatoapp.dish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
