# Generated by Django 3.1.5 on 2021-08-14 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zomatoapp', '0007_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='zomatoapp.dish')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zomatoapp.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
