# Generated by Django 3.1.5 on 2021-08-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomatoapp', '0008_userproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='status',
            field=models.CharField(choices=[('accepted', 'order accepted'), ('preparing', 'Food is being prepared'), ('out for delievery', 'out for delievery'), ('done', 'Delieverd')], default='accepted', max_length=200),
        ),
    ]
