# Generated by Django 3.1.5 on 2021-08-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomatoapp', '0010_auto_20210816_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='status',
            field=models.CharField(choices=[('order accepted', 'accept'), ('Food is being prepared', 'food is being prepared'), ('out for delievery', 'out for delievery'), ('delieverd', 'delieverd')], default='accepted', max_length=200),
        ),
    ]
